/**
 * Provider configuration map.
 * Each provider specifies how to transform skills for its platform.
 */
export const providers = {
  'claude-code': {
    provider: 'claude-code',
    configDir: '.claude',
    pluginDir: '.claude-plugin',
    displayName: 'Claude Code',
    frontmatterFields: ['name', 'description', 'user-invocable', 'argument-hint'],
    placeholders: {
      model: 'Claude',
      config_file: 'CLAUDE.md',
      command_prefix: '/',
      ask_instruction: 'Ask the user',
      skills_path: './.claude/skills',
      hooks_path: './hooks/hooks.json',
    },
  },
  cursor: {
    provider: 'cursor',
    configDir: '.cursor',
    pluginDir: '.cursor-plugin',
    displayName: 'Cursor',
    frontmatterFields: ['name', 'description'],
    placeholders: {
      model: 'Claude',
      config_file: '.cursorrules',
      command_prefix: '/',
      ask_instruction: 'Ask the user',
      skills_path: './.cursor/skills',
      hooks_path: './hooks/hooks.json',
    },
  },
  gemini: {
    provider: 'gemini',
    configDir: '.gemini',
    pluginDir: '.gemini',
    displayName: 'Gemini',
    frontmatterFields: ['name', 'description'],
    placeholders: {
      model: 'Gemini',
      config_file: 'GEMINI.md',
      command_prefix: '/',
      ask_instruction: 'Ask the user',
      skills_path: './.gemini/skills',
      hooks_path: './hooks/hooks.json',
    },
  },
  codex: {
    provider: 'codex',
    configDir: '.codex',
    pluginDir: '.codex',
    displayName: 'Codex',
    frontmatterFields: ['name', 'description'],
    placeholders: {
      model: 'GPT',
      config_file: 'AGENTS.md',
      command_prefix: '$',
      ask_instruction: 'Ask the user',
      skills_path: './.codex/skills',
      hooks_path: './hooks/hooks.json',
    },
  },
  agents: {
    provider: 'agents',
    configDir: '.agents',
    pluginDir: '.agents',
    displayName: 'Agents (Copilot)',
    frontmatterFields: ['name', 'description'],
    placeholders: {
      model: 'GPT',
      config_file: 'AGENTS.md',
      command_prefix: '/',
      ask_instruction: 'Ask the user',
      skills_path: './.agents/skills',
      hooks_path: './hooks/hooks.json',
    },
  },
  kiro: {
    provider: 'kiro',
    configDir: '.kiro',
    pluginDir: '.kiro',
    displayName: 'Kiro',
    frontmatterFields: ['name', 'description'],
    placeholders: {
      model: 'Claude',
      config_file: '.kiro/rules',
      command_prefix: '/',
      ask_instruction: 'Ask the user',
      skills_path: './.kiro/skills',
      hooks_path: './hooks/hooks.json',
    },
  },
  opencode: {
    provider: 'opencode',
    configDir: '.opencode',
    pluginDir: '.opencode',
    displayName: 'OpenCode',
    frontmatterFields: ['name', 'description'],
    placeholders: {
      model: 'Claude',
      config_file: 'AGENTS.md',
      command_prefix: '/',
      ask_instruction: 'Ask the user',
      skills_path: './.opencode/skills',
      hooks_path: './hooks/hooks.json',
    },
  },
};
